### ISSUE TITLE
Note about versioning scheme changes

### ISSUE THREAD

**Issue by agoose77** [jacobtomlinson/website#170] opened 2023-06-05 18:16 UTC
In https://jacobtomlinson.dev/posts/2023/sometimes-i-regret-using-calver/ you remark that it's hard to switch between version schemes.

I thought it would be interesting to point out this hidden gem from PEP 440 — [version epochs](https://peps.python.org/pep-0440/#version-epochs). With a higher version epoch, it's possible to signify that the versioning scheme has changed.

**Comment by jacobtomlinson** [comment] 2023-06-06 15:59
Hey there! Thanks for opening this. 

I similarly thought epochs were the answer to this, but they don't quite work the way users would intuitively expect so may cause more of a headache.

I was discussing this with @minrk and others a few months ago (although I can't find the original conversation now). Check out this repo with some examples of the behaviour and challenges https://github.com/minrk/epicepoch

**Comment by minrk** [comment] 2023-06-07 08:10
I found the discussion [here](https://hachyderm.io/@_jacobtomlinson@fosstodon.org/109700093864103120). The gist is that pip would need to change its handling of implicit epochs for it to work well, and I think it's solvable if folks want to work on it (probably warrants a PEP, which is tiring to consider for such a relatively narrow use case). I think it's worth writing up how epochs _could_ work that would make this transition more feasible. It doesn't have anything to do with what epochs _mean_ (pep440 covers that), the issue is mainly in the installer's handling of _unspecified_ epochs in version constraints, which I don't think PEP440 dictates. It's also worth mentioning that epochs are a PEP440 thing that pip may understand (if not how we'd like it to), but other packaging systems like conda may not have equivalents and that becomes a second hurdle to adoption in packages that are distributed via multiple channels.

**Comment by jacobtomlinson** [comment] 2023-06-19 15:15
Thanks for the response @minrk. That pretty much sums up my feelings too. This discussion seems to have come to an end so I'm going to close this issue.

**Closed by jacobtomlinson** 2023-06-19 15:15 UTC
